---
title: "BioInfo_Projekt"
author: "Me"
date: "2023-05-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("readxl")
library(readxl)

install.packages("sf")
library(sf)

install.packages("sp")
library(sp)

install.packages("terra")
library(terra)
```

  #Daten einlesen
```{r}
  #temperature 
  thailand_t2m = read_excel(file.choose("era5_data_2006_2020_thailand_monmean.xlsx"),sheet = 3)



#dengue
dengue_cases_thailand = read_excel(file.choose())



```


```{r}
#max function
f_max = function(x){
  max(x[5:19])
}
#min function 
f_min = function(x){
  min(x[5:19])
  }
```


```{r}
#Lowest temp of cambodia data
cambodia_t2m_daymin = as.data.frame(cambodia_t2m_daymin)
min_t = apply(cambodia_t2m_daymin,1,function(x){
  min(x[5:19])
  })
cambodia_t2m_daymin[which.min(min_t),2]
```


```{r}
# Sind die districts im norden oder im Süden? - Thailand - klappt noch nicht ganz
median_long_thai = median($Longitude) 
 
apply(_tp, 1, function(x) {
  if (x[3] > median_long_thai) {
    print(x[[2]])
    print("North") 
  }
  else 
    print(x[[2]])
    print("South")
})
```