---
title: "BioInfo_Projekt"
author: "Me"
date: "2023-05-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("readxl")
library(readxl)
```

#Daten einlesen
```{r}
#Cambodia
cambodia_t2m_daymax = read_excel(file.choose())
cambodia_t2m_daymin = read_excel(file.choose(),sheet = 2)
cambodia_tp = read_excel(file.choose(),sheet = 3)

#Laos
laos_t2m_daymax = read_excel(file.choose())
laos_t2m_daymin = read_excel(file.choose(),sheet = 2)
laos_tp = read_excel(file.choose(),sheet = 3)

#dengue
dengue_cases = read_excel(file.choose(),sheet = 2)
dengue_deaths = read_excel(file.choose(),sheet = 3)


```

```{r}
#Highest temp of cambodia data
cambodia_t2m_daymax = as.data.frame(cambodia_t2m_daymax)

max_t = apply(cambodia_t2m_daymax,1,function(x){
  max(x[5:19])
  })

cambodia_t2m_daymax[which.max(max_t),2]
```



```{r}
#max tp of cambodia data
cambodia_tp = as.data.frame(cambodia_tp)

max_value = which.max(apply(cambodia_tp, 1, function(x) {
 max(x[5:19])
}))
cambodia_tp[max_value, 2]
```


```{r}
# Sind die districts im norden oder im Süden? - Cambodia - klappt noch nicht ganz
median_long_cam = median(cambodia_tp$Longitude) 
 
apply(cambodia_tp, 1, function(x) {
  if (x[3] > median_long_cam) {
    print(x[[2]])
    print("North") 
    
  }
  else 
    print(x[[2]])
    print("South")
    
    
  
})


```


