---
title: "Bioinfo_Projekt_Einlesen"
author: "Frederik Racky"
date: "2023-05-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(dplyr)
```


##Einlesen der Tabellen und umwandeln der Tabellen in data frames
```{r}

Endung <- "_dengue_extracted.xlsx"
Anfang <- "Dengue"

for (i in 2006:2020) {
  Name <- paste0(i, Endung) #erstellen das Dateinamens
  Name_df <- paste0(Anfang, i) 
  assign(Name_df, read_excel(Name)) #erstellen der Variable und zuweisen der Excel-Tabelle 
  as.data.frame(Name_df) #umwandeln der Tabelle in ein Data-Frame
  
  Name_df$A <- paste0(Name_df$A, i) 
}


```

```{r}

Endung <- "_dengue_extracted.xlsx"
Anfang <- "Dengue"

for (i in 2006:2020) {
  a = i
  Dateiname <- paste0(i, Endung) #erstellen das Dateinamens
  Name_df <- paste0(Anfang, i) 
  assign(Name_df, read_excel(Dateiname)) #erstellen der Variable und zuweisen der Excel-Tabelle
  
  df_dengue <- get(Name_df)
  vec_data_names <- vector("character")
  
  vec_data_names <- sapply(df_dengue$`Reporting areas`, function(g) {
    paste(g[1], a)
  })
  data_names <- matrix(vec_data_names,nrow = 77, ncol = 1)
  df_dengue <- cbind(data_names, df_dengue)
  assign(Name_df,df_dengue)
}
```

##Einlesen der Tabellen und umwandeln der Tabellen in data frames
```{r}
library(readxl)
library(dplyr)

Endung <- "_dengue_extracted.xlsx"
Anfang <- "Dengue"

for (i in 2006:2020) {
  a = i
  Dateiname <- paste0(i, Endung) #erstellen das Dateinamens
  Name_df <- paste0(Anfang, i) 
  assign(Name_df, read_excel(Dateiname)) #erstellen der Variable und zuweisen der Excel-Tabelle
  
  df_dengue <- get(Name_df)
  vec_data_names <- vector("character")
  
  vec_data_names <- sapply(df_dengue$`Reporting areas`, function(g) {
    paste(g[1], a)
  })
  data_names <- matrix(vec_data_names,nrow = 77, ncol = 1)
  df_dengue <- cbind(data_names, df_dengue)
  assign(Name_df,df_dengue)
}
total_years = data.frame()
for (i in 2006:2020){
  a = get(paste0("Dengue",i))
  total_years = rbind(total_years, a)
}
```

#Rows als Zeitachse mit Monaten
```{r}
m = 1
data_total = data.frame(col1 = character(0), col2 = character(0), col3 = numeric(0), month = character(0))
colnames(data_total) = c("data_names", "Reporting areas", "dengue_cases", "month")
sorted_total_years = total_years[order(total_years$"Reporting areas"),]
for (k in 1:1155){
  for (j in 3:14){
    square <- sorted_total_years[k, c(1, 2, j)]
    month = colnames(square[3])
    square <- cbind(square,month)
    colnames(square) = c("data_names", "Reporting areas", "dengue_cases", "month")
    data_total <- rbind(data_total, square)
    colnames(data_total) = c("data_names", "Reporting areas", "dengue_cases", "month")
    data_total[m,1] = paste(data_total[m,1], month[1])
    m = m + 1
  }
}
```

```{r}
Dengue_2006$Districtnumber <- seq(from=1, to=77) #nummerieren der Distrikte
Dengue_2006_Di = Dengue_2006[, c(ncol(Dengue_2006), 1:(ncol(Dengue_2006)-1))] #verschieben der distriktnummer in die erste Zeile

```






