---
title: "Dana_Testdokument_Tempplots"
output: html_document
date: "2023-06-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data_total
```

```{r}
#ggplot template

# Libraries
library(ggplot2)

# create data
xValue <-
yValue <- 
data <- data.frame(xValue,yValue)

# Plot
ggplot(data, aes(x=xValue, y=yValue)) +
  geom_line()

```

Temperature of amnat charoen over the years

```{r}
month_dates <- seq(as.Date("2006-01-01"), as.Date("2020-12-01"), by = "month", format = "%m")
plot(x = month_dates[c(1:180)], y = data_total$temperature[c(1:180)], type = "l",xlab="Time", ylab="Temperature", col="red")
lmodel=lm(data_total$temperature[c(1:180)] ~ month_dates[c(1:180)])
abline(lmodel,col="blue")
axis(4, seq(20,32))


```

algorithm test for 01/2006

```{r}

  tempvec_01_2006 <- c()
  for (n in c(1:77)) {
   temp_01_2006 <- data_total$temperature[1 + 180*n]
   tempvec <- c(tempvec, temp_01_2006)
    
  }
tempvec 
```

temperature of amnat charoen over the years

```{r}
month_dates <- seq(as.Date("2006-01-01"), as.Date("2020-12-01"), by = "month", format = "%m")
plot(x = month_dates[c(1:180)], y = data_total$temperature[c(1:180)], type = "l",xlab="Time", ylab="Temperature", col="red", main="Temperature in Amnat Charoen")
lmodel=lm(data_total$temperature[c(1:180)] ~ month_dates[c(1:180)])
abline(lmodel,col="blue")
axis(4, seq(20,32))


```

creating vector of mean temp for thailand for every month

```{r}

 mean_tempvec <- c()
for (month in c(1:180)) {
   tempvec <- c()
  for (district in c(1:77)) {
   temp <- data_total$temperature[month + 180*(district-1)]
   tempvec <- c(tempvec,temp)
  }
 mean_tempvec <- c(mean_tempvec,mean(tempvec))
 }
mean_tempvec
```

*linear (or other) regression of temperature*

```{r}
lmodel_thailand_temp = lm(mean_tempvec ~ month_dates[c(1:180)])

```

divide Thailand into North, South, ... region to plot individual Temperature plots and compare regions

```{r}


```

#plot of temperature in thailand from 2006 to 2022

```{r}
month_dates <- seq(as.Date("2006-01-01"), as.Date("2020-12-01"), by = "month", format = "%m")
plot(x = month_dates[c(1:180)], y = mean_tempvec, type = "l",xlab="Time", ylab="Temperature", col="red")

abline(lmodel_thailand_temp,col="blue")
axis(4, seq(20,32))
```

ggplot

```{r}

# Libraries
library(ggplot2)

# create data
xValue <- month_dates
yValue <- mean_tempvec
data <- data.frame(xValue,yValue)

# Plot


ggplot() +
  geom_line(data, mapping=aes(x=xValue, y=yValue)) +
   stat_smooth(method = "lm", col = "red", mapping=aes(x=xValue, y=yValue)) +
  xlab("Years") +
  ylab("Temperature [°C]")


```

```{r}
install.packages("readxl")
install.packages("nlme")
install.packages("gam")
install.packages("sdm")
install.packages("raster")
install.packages("ncdf4")

library (readxl)
library(nlme)
library(gam)
library(sdm)
library(raster)
library(ncdf4)
```
